type LectureTemplateInput = {
  code: string;
  title: string;
  chapter: string;
  description: string | null;
  templatePath: string;
};

type TaskTemplateInput = {
  taskId: string;
  teacherName: string;
  lecture: LectureTemplateInput;
};

export function buildInitialTexSource({ taskId, teacherName, lecture }: TaskTemplateInput) {
  const description = lecture.description?.trim() || "待补充讲义说明";

  return [
    "% Auto-generated by admin assignment flow",
    `% Template: ${lecture.templatePath}`,
    `% Task: ${taskId}`,
    "\\documentclass{article}",
    "\\usepackage[UTF8]{ctex}",
    "",
    `\\title{${lecture.title}}`,
    `\\author{${teacherName}}`,
    "\\date{}",
    "",
    "\\begin{document}",
    "\\maketitle",
    "",
    `\\section*{讲义编号}`,
    lecture.code,
    "",
    `\\section*{章节}`,
    lecture.chapter,
    "",
    `\\section*{说明}`,
    description,
    "",
    "\\section*{正文}",
    "请从这里开始编写 main.tex 内容。",
    "",
    "\\end{document}",
    "",
  ].join("\n");
}
