type LectureTemplateInput = {
  title: string;
  description: string | null;
  templatePath: string;
};

type TaskTemplateInput = {
  taskId: string;
  teacherName: string;
  lecture: LectureTemplateInput;
};

export function buildInitialTexSource({ taskId, teacherName, lecture }: TaskTemplateInput) {
  const description = lecture.description?.trim() || "待补充讲义说明";
  const targetFileName = lecture.templatePath.split("/").pop() || "lecture.tex";

  return [
    "% Auto-generated by admin assignment flow",
    `% Task: ${taskId}`,
    "\\documentclass{article}",
    "\\usepackage[UTF8]{ctex}",
    "",
    `\\title{${lecture.title}}`,
    `\\author{${teacherName}}`,
    "\\date{}",
    "",
    "\\begin{document}",
    "\\maketitle",
    "",
    `\\section*{说明}`,
    description,
    "",
    "\\section*{正文}",
    `请从这里开始编写 ${targetFileName} 内容。`,
    "",
    "\\end{document}",
    "",
  ].join("\n");
}
