ALTER TYPE "LectureStatus" RENAME VALUE 'DRAFT' TO 'TODO';
ALTER TYPE "LectureStatus" RENAME VALUE 'ACTIVE' TO 'ING';
ALTER TYPE "LectureStatus" RENAME VALUE 'ARCHIVED' TO 'DONE';

ALTER TABLE "lectures"
  ALTER COLUMN "status" SET DEFAULT 'TODO';
